In [31]:
import tensorflow.keras.utils as utils
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
import numpy as np
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [32]:
# 1.데이터 생성하기
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    'handwriting_shape/train',
    target_size=(24, 24),
    batch_size=3,
    class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
    'handwriting_shape/test',
    target_size=(24,24),
    batch_size=3,
    class_mode='categorical')
    

Found 45 images belonging to 3 classes.
Found 15 images belonging to 3 classes.


In [33]:
# 모델 구성하기
model =Sequential()
model.add(Conv2D(32, kernel_size=(3,3),
                activation='relu',
                input_shape =(24,24,3)))
model.add(Conv2D(64, (3,3),activation = 'relu'))
model.add(MaxPooling2D(pool_size = (2,2)))
model.add(Flatten())
model.add(Dense(128, activation = 'relu'))
model.add(Dense(3, activation= 'softmax'))

In [34]:
# 모델학습과정 설정하기
model.compile(loss='categorical_crossentropy', optimizer = 'adam', metrics=['accuracy'])


In [35]:
# 모델 학습시키기
model.fit_generator(
        train_generator,
        steps_per_epoch=15,
        validation_data=test_generator,
        validation_steps=5)

15/15 [==============================] - 1s 46ms/step - loss: 0.6356 - accuracy: 0.7333 - val_loss: 0.4049 - val_accuracy: 0.7333


In [36]:
# 모델 평가하기
print("--Evaluate--")
scores = model.evaluate_generator(test_generator, steps=5)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

--Evaluate--
accuracy: 73.33%


In [37]:
print("-- Predict --")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --
{'circle': 0, 'rectangle': 1, 'triangle': 2}
[[0.092 0.855 0.054]
 [0.007 0.015 0.977]
 [0.597 0.337 0.065]
 [0.051 0.943 0.006]
 [0.016 0.056 0.929]
 [0.066 0.920 0.014]
 [0.468 0.425 0.106]
 [0.457 0.500 0.043]
 [0.003 0.004 0.992]
 [0.003 0.007 0.989]
 [0.141 0.258 0.601]
 [0.002 0.002 0.995]
 [0.057 0.920 0.022]
 [0.287 0.183 0.531]
 [0.403 0.539 0.058]]
