## 1. random 함수를 활용하여 로또 추첨기 만들기

In [33]:
a=[]
while (len(a) < 6):
    b=int(46*random.random())
    if (b==0 or b==46):
        continue
    a.append(b)
    a=list(set(a))
print(sorted(a))


[4, 17, 24, 32, 35, 45]


In [26]:
l = []
print(len(l))

0


## 2. 3단, 6단을 제외한 구구단 만들기(반복문사용)

In [6]:
for j in range(2,10):
    if (j == 3) or (j==6):
        continue
    print(j, "단")
    for i in range(1,10):
        print("{} X {} = {}".format(j,i,j*i))
    print()

2 단
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18

4 단
4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36

5 단
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45

7 단
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63

8 단
8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72

9 단
9 X 1 = 9
9 X 2 = 18
9 X 3 = 27
9 X 4 = 36
9 X 5 = 45
9 X 6 = 54
9 X 7 = 63
9 X 8 = 72
9 X 9 = 81



## 3. 리스트 중복을 제거하고 역순으로 정렬하기

In [8]:
a = [1,1,1,4,2,5,6,7,3,5,6,7,6,7,8,4,3,5,6,7,2,6,2,4,2,9,8,6,7,4,5,3,2]
b = set(a)
c = sorted(list(b), reverse = True)
print(c)

[9, 8, 7, 6, 5, 4, 3, 2, 1]


## 4. 5개 이상의 특징을 가진 동물분류기

In [105]:
import random
import numpy as np

data = []
#개, 돼지, 호랑이, 얼룩말, 치타
#(높이, 길이, 무게, 먹는 양, 달리기속도)
for i in range(50):
    #data.append(      키높이            머리에서 꼬리까지 길이      몸무게                 샤료먹는 양             달리기 속도)
    data.append([random.randint(20, 40),random.randint(30, 80), random.randint(20, 50), random.randint(1, 20), random.randint(10, 40)]) #개
    data.append([random.randint(40, 60),random.randint(60, 150), random.randint(100, 150), random.randint(20, 30), random.randint(5, 10)]) #돼지
    data.append([random.randint(50, 100),random.randint(130, 200), random.randint(200, 250), random.randint(10, 25), random.randint(50, 80)]) #호랑이
    data.append([random.randint(80, 120),random.randint(100, 150), random.randint(90, 120), random.randint(10, 15), random.randint(30, 90)]) #얼룩말
    data.append([random.randint(50, 80),random.randint(80, 130), random.randint(80, 100), random.randint(5, 15), random.randint(80, 110)]) #치타

points = [[random.randint(20, 120),random.randint(60, 200),random.randint(20, 250),random.randint(1, 30),random.randint(5, 110)],
                 [random.randint(20, 120),random.randint(60, 200),random.randint(20, 250),random.randint(1, 30),random.randint(5, 110)],
                 [random.randint(20, 120),random.randint(60, 200),random.randint(20, 250),random.randint(1, 30),random.randint(5, 110)],
                 [random.randint(20, 120),random.randint(60, 200),random.randint(20, 250),random.randint(1, 30),random.randint(5, 110)],
                 [random.randint(20, 120),random.randint(60, 200),random.randint(20, 250),random.randint(1, 30),random.randint(5, 110)]]


def dist(x,y):
    return np.sqrt((x[0]-y[0])**2 +(x[1]-y[1])**2+(x[2]-y[2])**2+(x[3]-y[3])**2+(x[4]-y[4])**2)

fullcnt = 0 
while fullcnt < 10: #총 10번 시행
    #각 데이터를 기준으로 가장 가까운 점을 찾는다
    temp = [[],[],[],[],[]]
    for i in data:
        distance = []
        for k in range(0,5):
            distance.append(dist(points[k], i))
        temp[ distance.index( min(distance) ) ].append(i)
# 각 동물 = temp[i]
# 동불별로 그룹화된 데이터들을 평균내서 새로운 기준점을 만든다
    for i in range(0,5):
        sum_arr = np.zeros(5)
        count = 0
        temp[i] = np.array(temp[i])
        for n in temp[i]:
            sum_arr+=n
            count+=1
        points[i] = np.array(sum_arr)/count
    #print(points)
    fullcnt += 1

print("결과출력")
for i in points:
    print(i)

        
        
    

결과출력
[ 50.15686275 102.76470588 123.19607843  23.90196078   7.78431373]
[ 81.52173913 181.82608696 230.26086957  15.43478261  67.17391304]
[ 71.96296296 148.77777778 222.11111111  16.40740741  64.25925926]
[30.88 56.3  36.06 10.58 26.  ]
[ 80.84848485 114.03030303  97.17171717  11.17171717  76.6969697 ]


## 5. 피보나치 수열 출력 프로그램

In [111]:
n = [0, 1, 1]
print("  1 번째 피보나치 수: {}".format(n[1]))
for i in range(2, 101):
    print("{:3d} 번째 피보나치 수: {}".format(i,n[2]))
    n[0] = n[1]
    n[1] = n[2]
    n[2] = n[0]+n[1]

  1 번째 피보나치 수: 1
  2 번째 피보나치 수: 1
  3 번째 피보나치 수: 2
  4 번째 피보나치 수: 3
  5 번째 피보나치 수: 5
  6 번째 피보나치 수: 8
  7 번째 피보나치 수: 13
  8 번째 피보나치 수: 21
  9 번째 피보나치 수: 34
 10 번째 피보나치 수: 55
 11 번째 피보나치 수: 89
 12 번째 피보나치 수: 144
 13 번째 피보나치 수: 233
 14 번째 피보나치 수: 377
 15 번째 피보나치 수: 610
 16 번째 피보나치 수: 987
 17 번째 피보나치 수: 1597
 18 번째 피보나치 수: 2584
 19 번째 피보나치 수: 4181
 20 번째 피보나치 수: 6765
 21 번째 피보나치 수: 10946
 22 번째 피보나치 수: 17711
 23 번째 피보나치 수: 28657
 24 번째 피보나치 수: 46368
 25 번째 피보나치 수: 75025
 26 번째 피보나치 수: 121393
 27 번째 피보나치 수: 196418
 28 번째 피보나치 수: 317811
 29 번째 피보나치 수: 514229
 30 번째 피보나치 수: 832040
 31 번째 피보나치 수: 1346269
 32 번째 피보나치 수: 2178309
 33 번째 피보나치 수: 3524578
 34 번째 피보나치 수: 5702887
 35 번째 피보나치 수: 9227465
 36 번째 피보나치 수: 14930352
 37 번째 피보나치 수: 24157817
 38 번째 피보나치 수: 39088169
 39 번째 피보나치 수: 63245986
 40 번째 피보나치 수: 102334155
 41 번째 피보나치 수: 165580141
 42 번째 피보나치 수: 267914296
 43 번째 피보나치 수: 433494437
 44 번째 피보나치 수: 701408733
 45 번째 피보나치 수: 1134903170
 46 번째 피보나치 수: 1836311903
 47 번째 피보나치 수: 2971215073
 48 

## 재귀함수를 이용한 피보나치 수열

In [109]:
def fib(n):
    if n<2:
        print("+1")
        return 1
    else:
        print("f({})".format(n), end= ' ')
        return (fib(n-1)+fib(n-2))
    
n = int(input("n번째 피보나치 수를 입력하십시오"))
print("{:3d}번째 피보나치 수 : {}".format(n, fib(n)))

n번째 피보나치 수를 입력하십시오12
f(12) f(11) f(10) f(9) f(8) f(7) f(6) f(5) f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(3) f(2) +1
+1
+1
f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(5) f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(3) f(2) +1
+1
+1
f(6) f(5) f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(3) f(2) +1
+1
+1
f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(7) f(6) f(5) f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(3) f(2) +1
+1
+1
f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(5) f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(3) f(2) +1
+1
+1
f(8) f(7) f(6) f(5) f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(3) f(2) +1
+1
+1
f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(5) f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(3) f(2) +1
+1
+1
f(6) f(5) f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(3) f(2) +1
+1
+1
f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(9) f(8) f(7) f(6) f(5) f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(3) f(2) +1
+1
+1
f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(5) f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(3) f(2) +1
+1
+1
f(6) f(5) f(4) f(3) f(2) +1
+1
+1
f(2) +1
+1
f(3) f(2) +1
+1
+1
f(4) f(3) f(2) +1
+1
+